### ISSUE TITLE
question about the hello world example

### ISSUE THREAD

**Issue by zjin-lcf** [UCI-CARL/MotionEnergy#15]
In the hello world example, using a fixed constant for the srand() function doesn't show the same results across multiple runs. Is this expected ?
run 1:
0: mean activity = 0.439031
1: mean activity = 0.501078
2: mean activity = 0.317878
3: mean activity = 0.729056
4: mean activity = 0.502201
5: mean activity = 0.625352
6: mean activity = 0.563613
7: mean activity = 0.688112
8: mean activity = 0.438253
9: mean activity = 0.688300
run 2:
0: mean activity = 0.500670
1: mean activity = 0.563959
2: mean activity = 0.568377
3: mean activity = 0.504105
4: mean activity = 0.440226
5: mean activity = 0.625791
6: mean activity = 0.688198
7: mean activity = 0.562702
8: mean activity = 0.688510
9: mean activity = 0.563258

Thanks

**Comment by mbeyeler** [comment]
Sorry, I don't think anyone is maintaining this anymore and you asked your question so long ago that you probably don't care about the answer anymore. :)

It is expected because of the parallel execution on the GPU. Order of execution might be slightly different on each run leading to slightly different output
